version: '3.8'

services:
  personal-backend:
    build: ./personal-backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/mydatagpt
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=mydatagpt
      - FIREBASE_SERVICE_ACCOUNT=./src/mydatagpt-ee047-firebase-adminsdk-fbsvc-4584263bfa.json
    depends_on:
      - postgres
      - minio

  chatgpt-backend:
    build: ./chatgpt-backend
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"

  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - personal-backend
      - chatgpt-backend
      - frontend
      
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatagpt
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./personal-backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

volumes:
  postgres-data:
  minio-data:
