
name: Docker Publish and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: mastenmind/mydatagpt_mia:latest
          secrets: |
            "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
  
  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/${{ secrets.VPS_USERNAME }}
            mkdir -p app
            cd app
            
            echo "version: '3.8'
            services:
              mydatagpt:
                image: mastenmind/mydatagpt_mia:latest
                restart: always
                ports:
                  - '3000:3000'
                environment:
                  - GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            " > docker-compose.yml

            echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env
            
            docker-compose pull
            docker-compose up -d --remove-orphans
            echo "Deployment successful!"
